# Generated by Django 4.2.6 on 2023-10-17 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_alter_person_birth_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='character_name',
        ),
        migrations.AddField(
            model_name='moviecredit',
            name='character_name',
            field=models.CharField(default='NA', max_length=128),
        ),
    ]
