# Generated by Django 4.2.6 on 2023-10-19 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_remove_person_character_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='atmdb_id',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
